import "dotenv/config";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import { apiRouter } from "./routes/api.js";
import { errorHandler } from "./middleware/errorHandler.js";
const app = express();
const port = Number(process.env.PORT ?? 4000);
const corsOrigin = process.env.CORS_ORIGIN ?? "http://localhost:5173";
app.use(helmet()); app.use(cors({ origin: corsOrigin })); app.use(express.json({ limit: "100kb" }));
app.get("/health", (_req, res) => res.json({ status: "ok", service: "talentbridge-api" }));
app.use("/api", apiRouter); app.use((_req, res) => res.status(404).json({ error: "Route not found" })); app.use(errorHandler);
app.listen(port, () => console.log(`TalentBridge API listening on http://localhost:${port}`));
